### ISSUE TITLE
XCB functions

### ISSUE THREAD

**Issue by Yamakaky** [gtk-rs/cairo#101]
Do you plan to add bindings to https://cairographics.org/manual/cairo-XCB-Surfaces.html, at least in cairo-sys? I need them to implement 29.2.5 at https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#VkXcbSurfaceCreateInfoKHR.

**Comment by GuillaumeGomez** [comment]
I can if you need them. I'll try to do it this evening.

**Comment by Yamakaky** [comment]
Cool, thanks!

**Comment by Yamakaky** [comment]
Is it possible to initialise the surface using `cairo_sys` then create a Surface using `FromGlibPtr`?
