### ISSUE TITLE
Add missing surface functions

### ISSUE THREAD

**Issue by Yamakaky** [gtk-rs/cairo#104]
https://www.cairographics.org/manual/cairo-surfaces.html

**Comment by federicomenaquintero** [comment]
Are there specific functions which you need and which are not available yet?

**Comment by GuillaumeGomez** [comment]
I added some but don't know if they fulfil @Yamakaky's needs.

**Comment by Yamakaky** [comment]
For now, I have everything I need, thanks!

**Comment by federicomenaquintero** [comment]
Yay!
