### ISSUE TITLE
Derive Debug on a lot of structs

### ISSUE THREAD

**Issue by Yamakaky** [gtk-rs/cairo#112]

**Comment by GuillaumeGomez** [comment]
Well, it won't prove much information except maybe the name of the type? (if it is what you had in mind)

**Comment by Yamakaky** [comment]
The main problem with the current status is that you can't auto-derive Debug with a struct from this crate as member.

Yeah, just show the type, with maybe some more info if available.

**Comment by sdroege** [comment]
I don't think any are missing at this point
