### ISSUE TITLE
RFC: MatrixTrait::try_invert()

### ISSUE THREAD

**Issue by federicomenaquintero** [gtk-rs/cairo#116]
I appreciate how MatrixTrait::invert() actually ensures that the matrix is invertible, and panics otherwise; it has caught a lot of bugs in librsvg.

Now, I need to know if a matrix is actually invertible, to validate user-supplied data (actually, transformations that come from an SVG file).

The quick-and-dirty way is to call ffi::cairo_matrix_invert() by hand and test the result.

A more idiomatic way could be to have this in MatrixTrait:

```
pub trait MatrixTrait {
    ...
     fn try_invert(&self) -> Result <Matrix, Status>;
    ...
}
```
What do you think?  I can submit a pull request for this if you like the API.

**Comment by GuillaumeGomez** [comment]
Seems reasonable and a good idea.

**Comment by federicomenaquintero** [comment]
This has been merged; closing.
