### ISSUE TITLE
Add unsafe from_raw method for FontOptions (and others)

### ISSUE THREAD

**Issue by johncf** [gtk-rs/cairo#119]
I would like to suggest adding the following method to `FontOptions`:

```rust
    unsafe fn from_raw(ptr: *mut cairo_font_options_t) -> FontOptions {
        FontOptions(ptr)
    }
```

Side note: The inner pointer in `FontFace` is public. This is a bug, right? Since I can do unsafe things with this without using `unsafe` tag. Adding `from_raw` would be the correct alternative.

**Comment by EPashkin** [comment]
In gtk-rs normally we use `FromGlibPtrNone` or `FromGlibPtrFull` to this.
Cairo package not fully use this convention due we mostly focused on gtk/gdk as cairo don't have proper `cairo-1.0.gir` file.

**Comment by johncf** [comment]
@EPashkin True. But this functionality is needed to implement certain things such as [this](https://github.com/RazrFalcon/pangocairo-rs/blob/9645c64/src/lib.rs#L72). (Or can it be achieved another way?)

**Comment by EPashkin** [comment]
As `PangoCairo-1.0.gir` says `transfer-ownership="none" nullable="1"` for return value for `pango_cairo_context_get_font_options` then it need be
```rust
fn get_font_options(&self) -> Option<cairo::FontOptions> {
    from_glib_none(ffi::pango_cairo_context_get_font_options(self.to_glib_none().0)
}
```
in cairo implementation IMHO looks something like [Context](https://github.com/gtk-rs/cairo/blob/master/src/context.rs#L44-L68) with `cairo_font_options_copy` instead `cairo_reference`

**Comment by johncf** [comment]
@EPashkin Thanks for pointing it out. I'm really new at this, and don't really know about how to use `gir`. I found the [`gir` repo](https://github.com/gtk-rs/gir-files), but can you point me to any docs of how it is used?

Anyway, I tried the solution you suggested and on compilation, gets the following error:

```
   Compiling pangocairo v0.1.0 (file:///home/john/dev/00-try/pangocairo-rs)
error[E0277]: the trait bound `cairo::FontOptions: glib::translate::FromGlibPtrNone<*const cairo_sys::cairo_font_options_t>` is not satisfied
  --> src/lib.rs:71:9
   |
71 |         from_glib_none(ffi::pango_cairo_context_get_font_options(self.to_glib_none().0))
   |         ^^^^^^^^^^^^^^ the trait `glib::translate::FromGlibPtrNone<*const cairo_sys::cairo_font_options_t>` is not implemented for `cairo::FontOptions`
   |
   = note: required because of the requirements on the impl of `glib::translate::FromGlibPtrNone<*const cairo_sys::cairo_font_options_t>` for `std::option::Option<cairo::FontOptions>`
   = note: required by `glib::translate::from_glib_none`

error: aborting due to previous error

error: Could not compile `pangocairo`.

To learn more, run the command again with --verbose.
```

Is it because "`cairo` doesn't follow this convention" as you said before? Would this be fixed anytime soon?

**Comment by EPashkin** [comment]
As cairo can't be processed by Gir all code in cairo and cairo-sys need be written by hand.
So it won't fixed until someone that need it and can check that it really works do it 😉

**Comment by johncf** [comment]
Hmm... I wonder who that _someone_ will be ... :smile: 

After looking around a bit, I understand that `impl FromGlibPtrNone` like [this](https://github.com/gtk-rs/cairo/blob/master/src/context.rs#L53-L60) is enough to get a [free `impl`](https://github.com/gtk-rs/glib/blob/d6fe8c68/src/translate.rs#L750-L756) for the `Option<T>` type too.

So shall I give a PR `impl`-ing `FromGlibPtrNone` and `ToGlibPtr` for `FontOptions`?

Also, what about `FontFace`? Shall I make the inner pointer private, and implement these two traits for it too? Will it be a breaking change?

**Comment by EPashkin** [comment]
IMHO as `FontFace` have `get_ptr()` making field private can be done if class have `FromGlibPtrXXX`.
Your PR will be welcomed if you can check that addition works.
