### ISSUE TITLE
write_to_png functionality

### ISSUE THREAD

**Issue by guanqun** [gtk-rs/cairo#121]
I see there seems to an API called "write_to_png" on https://docs.rs/crate/cairo-rs/0.1.0/source/src/image_surface_png.rs, but it's not anymore in latest version, any reason it gets removed?

Then how can I save the image surface to a file?

Thanks,

**Comment by EPashkin** [comment]
It under `png` feature

**Comment by guanqun** [comment]
You mean crate `png`? Then how can get the raw data from {{ImageSurface}}?

**Comment by EPashkin** [comment]
I mean http://doc.crates.io/specifying-dependencies.html#choosing-features
```toml
[dependencies.cairo-rs]
version = "^0"
features = [ "png" ]
```
then use function on image.

**Comment by EPashkin** [comment]
@GuillaumeGomez, there strange `stream` parameter type for https://github.com/gtk-rs/cairo/blob/master/src/image_surface_png.rs#L80.
It not need changed to `stream: &mut W` ? Same with `create_from_png`

**Comment by GuillaumeGomez** [comment]
Oh damn! Yes it should!

**Comment by guanqun** [comment]
Thank you both, now I can use this function.
