### ISSUE TITLE
Duplicate types of enums in cairo-sys

### ISSUE THREAD

**Issue by johncf** [gtk-rs/cairo#124]
The following enum types:
```
enums::{
    Antialias,
    Content,
    Extend,
    FillRule,
    LineCap,
    LineJoin,
    Filter,
}
```
have duplicate struct types:
```rust
#[repr(C)]
pub struct cairo_antialias_t(c_void);
#[repr(C)]
pub struct cairo_content_t(c_void);
#[repr(C)]
pub struct cairo_extend_t(c_void);
#[repr(C)]
pub struct cairo_fill_rule_t(c_void);
#[repr(C)]
pub struct cairo_line_cap_t(c_void);
#[repr(C)]
pub struct cairo_line_join_t(c_void);
#[repr(C)]
pub struct cairo_filter_t(c_void);
```
which are unused inside `cairo_sys` repository, but for some reason, seems to be [used](http://gtk-rs.org/docs/gdk_sys/fn.gdk_window_create_similar_surface.html) in other repositories. ([Here](https://github.com/johncf/gtk-scribble-app/blob/master/src/main.rs#L35) is a example usage which does not work.)

**Comment by EPashkin** [comment]
Your right. Only `cairo_content_t` currently used in your crates. Seems it need changed to `pub type cairo_content_t = Content;`.
Not sure what do with other.

**Comment by johncf** [comment]
What I don't understand is where does gir get the type name information from. How does it generate `cairo::cairo_content_t` in [this line](https://github.com/gtk-rs/sys/blob/master/gdk-sys/src/lib.rs#L4303)? Here are the relevant lines in [`gdk-3.0.gir`](https://raw.githubusercontent.com/gtk-rs/gir-files/71d73f05707e0f4800274c6440a0d493fbe71646/Gdk-3.0.gir):

```
          <parameter name="content" transfer-ownership="none">
            <doc xml:space="preserve">the content for the new surface</doc>
            <type name="cairo.Content" c:type="cairo_content_t"/>
          </parameter>
```

How to map `cairo.Content` to `cairo::enums::Content`?

**Comment by EPashkin** [comment]
`cairo_content_t` is single enum from this list that present in your cairo-1.0.gir.
And Gdk-3.0.gir include cairo and can use its types.
```xml
    <enumeration name="Content" c:type="cairo_content_t"
		 glib:type-name="CairoContent"
		 glib:get-type="cairo_gobject_content_get_type">
      <member name="COLOR"
              value="4096"
              c:identifier="CAIRO_CONTENT_COLOR"/>
      <member name="ALPHA"
              value="8192"
              c:identifier="CAIRO_CONTENT_ALPHA"/>
      <member name="COLOR_ALPHA"
              value="12288"
              c:identifier="CAIRO_CONTENT_COLOR_ALPHA"/>
    </enumeration>
```

**Comment by johncf** [comment]
Hmm... So is it okay if I send a PR with all those `struct` replaced with `pub type` aliases to enums (which will be `#[repr(C)]`-ed)?

PS: Why does cairo has `c:type` names in snake case, while other libraries with proper gir files have CamelCase `c:type` names? This got me confused a bit...

**Comment by EPashkin** [comment]
Thank you in advance for PR. It good that you have test case.
`#[repr(C)]` not works with type and enum already has it.

I don't know why cairo use snake case names
