### ISSUE TITLE
#[cfg(macos)] should be #[cfg(target_os = "macos")]

### ISSUE THREAD

**Issue by Znapi** [gtk-rs/cairo#135]
Unless there is a reason for this that I don't see, in the very few places that there are `#[cfg(macos)]`s, it should be `#[cfg(target_os = "macos")]`. I'm on macOS, and the compiler just throws out anything under a `#[cfg(macos)]`, making the quartz backend functions unusable.

I tried just replacing them, but it just revealed a few other errors within the functions themselves.

**Comment by Znapi** [comment]
Turns out it was an easy fix: #136

**Comment by EPashkin** [comment]
Strange, it seems worked for https://github.com/gtk-rs/cairo/issues/114 (@Yamakaky).
This time cargo has error, maybe really he cant check it.

**Comment by EPashkin** [comment]
Only found `target_family`'s is `unix` and `windows` in https://github.com/rust-lang/rust/tree/master/src/librustc_back/target
There also `target_os = "ios"` while seems `cairo` don't have [version](https://cairographics.org/download/) for it, but someone use it on IPhone.
So maybe right condition need be `#[cfg(any(target_os = "macos", target_os = "ios"))]`

**Comment by Znapi** [comment]
I just added `target_os = "ios"` to the pull request.
