### ISSUE TITLE
Need a wrapper for cairo_format_stride_for_width()

### ISSUE THREAD

**Issue by federicomenaquintero** [gtk-rs/cairo#145]
`ImageSurface.create_for_data()` calls `cairo_image_surface_create_for_data()`, and its `stride` parameter:

1. Needs to be aligned to 32 bits

1. Must have an absolute value greater than or equal to `cairo_format_stride_for_width()` for the corresponding image (negative strides are allowed for bottom-to-top images).

The only place I could find that actually figures out a `stride` is in `examples/src/cairo-threads.rs`, but that gets it from an existing `image_surface.get_stride()` - it doesn't create a buffer on its own.

So, for people who actually want to allocate their own buffers to pass to `ImageSurface.create_for_data()`, I think we need a wrapper for `cairo_format_stride_for_width()`.

**Comment by GuillaumeGomez** [comment]
It'd make things simpler indeed.

**Comment by federicomenaquintero** [comment]
This can be closed now that it's merged.
