### ISSUE TITLE
Can we consider implementation of `Send` for `Context`, `Surface`? 

### ISSUE THREAD

**Issue by application-developer-DA** [gtk-rs/cairo#175]
It seems that it should be possible to make `Context` and/or `Surface` sendable across the threads. Otherwise it's very limited as it does not allow the user to send the `Context` in case if it was just created in one thread and then being moved into another thread.

`rust-xcb` had the similar issue once, which was solved by introducing `thread` feature, which implements `Send` for certain types in order to allow passing `xcb::Connection` between threads.

I think it would be nice to have the similar thing here in `cairo-rs`.

**Comment by sdroege** [comment]
They are not `Send` in general. It depends on the backend (e.g. the Win32 backend is not `Send` at all while the Image surfaces are), and also refcounted things (like `Context` and `Surface`) must also be `Sync` if they are `Send` and that's unfortunately not the case with cairo.

@GuillaumeGomez This can be closed
