### ISSUE TITLE
Don't drop Pattern muti times

### ISSUE THREAD

**Issue by Brooooooklyn** [gtk-rs/cairo#183]
There is a bug while call `get_source` in context, there is a minimal example to show how to reproduce the bug:

```rs
fn main() {
  let surface = ImageSurface::create(Format::ARgb32,  100.0f64, 100.0f64).unwrap();
  let context = Context::new(&surface);
  context.get_source();
}
```

would caused panic:

```bash
Assertion failed: (CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&pattern->ref_count)), function cairo_pattern_destroy, file cairo-pattern.c, line 1125.
```

And it may be caused by https://github.com/gtk-rs/cairo/blob/master/src/patterns.rs#L137

It should not `Drop` pattern which created by `Context`.

**Comment by sdroege** [comment]
Possible. Can you provide a full testcase to reproduce the problem?

**Comment by fgilio** [comment]
Hi @sdroege, thanks for the quick response! I think it's related to other issue, I'll post and update if needed.

**Comment by sdroege** [comment]
> Hi @sdroege, thanks for the quick response! I think it's related to other issue, I'll post and update if needed.

Any news on this? :)

**Comment by fgilio** [comment]
While the error I see is that one in particular, I don't know this is the right repo to report it. I'm getting this error while converting PDF pages to JPGs using pdf.js and node-canvas (which relies on cairo).
So the error I get with some PDF pages is `Assertion failed: (CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&pattern->ref_count)), function cairo_pattern_destroy, file cairo-pattern.c, line 1127.`, but I guess this is not the right repo.

**Comment by sdroege** [comment]
Yes that's unrelated to this repository. This repository contains the Rust bindings for Cairo, not Cairo itself or whatever pdf.js/node-canvas are using.
