### ISSUE TITLE
ImageSurface::create_from_png produce AV on Windows for bad input

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/cairo#185]
Its reason why tests `invalid_png_yields_error`, `io_error_yields_cairo_read_error` causes failure in appveyor

**Comment by EPashkin** [comment]
Seems something in libcairo was updated in bad way.
Tests added in https://github.com/gtk-rs/cairo/pull/146 by @federicomenaquintero and currently it fails.
But on https://ci.appveyor.com/project/GuillaumeGomez/cairo-p0df1/build/1.0.329 it was passed

**Comment by federicomenaquintero** [comment]
If you narrow this down to a bug in Cairo upstream, could you please tell me about it? (Or, @GuillaumeGomez we can talk about it this week at the hackfest?)  I'm trying to fix things in Cairo upstream, so maybe I can handle this if I know what it's about :)

**Comment by EPashkin** [comment]
New cairo 1.15.12 don't panics, seems it was attempt optimizing usage `setjmp` in 1.15.10, that was reverted.
I tried restart appveyor for https://github.com/gtk-rs/cairo/pull/184 as final test, but it can't download rustup now.

**Comment by EPashkin** [comment]
Appveyor still used cairo-1.15.10-1

**Comment by EPashkin** [comment]
Added https://github.com/gtk-rs/cairo/pull/186 that use update pacman before installing gtk, it solved issue
