### ISSUE TITLE
Shouldn't Context mutably borrow the target surface?

### ISSUE THREAD

**Issue by YaLTeR** [gtk-rs/cairo#192]
Since the target surface contents are modified via the context.

**Comment by YaLTeR** [comment]
One use case I have in mind is having a shared read-only `ImageSurfaceData` which would still check for exclusiveness (since we can't see what the other references are doing), but would permit read-only access to the pixel contents enforced by a read-only borrow of an (exclusive) reference to an image surface.

Right now, however, it's not possible to do safely because even when an exclusive surface is borrowed read-only, you can still make a context on it and modify the pixel data.

**Comment by SimonSapin** [comment]
Modifications happen (effectively) through interior mutability. https://github.com/gtk-rs/cairo/issues/256 explains some more.

**Comment by sdroege** [comment]
@GuillaumeGomez Can you close this?

**Comment by GuillaumeGomez** [comment]
Sure!
