### ISSUE TITLE
cairo_pattern_reference: Assertion `CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&pattern->ref_count)' failed.

### ISSUE THREAD

**Issue by vhakulinen** [gtk-rs/cairo#195]
I'm getting following error when using `cairo::Pattern` with the latest git version: `cairo_pattern_reference: Assertion CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&pattern->ref_count)' failed.`, which results in a crash. This error is not occurring with version 0.3.

Here is related code snipped:

```rust
    let s = cr.get_target();
    // Create pattern which we can then "safely" draw to the surface. On X11, the pattern part was
    // not needed but on wayland it is - I suppose it has something to do with the underlaying
    // backbuffer.
    cr.push_group();
    let (_, y) = get_coords(ci.height, ci.width, dst_top - src_top, 0.0);
    cr.set_source_surface(&s, 0.0, y);
    cr.set_operator(cairo::Operator::Source);
    let (x1, y1, x2, y2) = get_rect(ci.height, ci.width, dst_top, dst_bot, left as f64, right as f64);
    let w = x2 - x1;
    let h = y2 - y1;
    cr.rectangle(x1, y1, w, h);
    cr.fill();

    // Get the pattern.
    let mut p = cr.pop_group();

    // Draw the parttern.
    cr.set_source(&mut p);
    cr.set_operator(cairo::Operator::Source);
    cr.rectangle(x1, y1, w, h);
    cr.fill();
    da.queue_draw_area(x1 as i32, y1 as i32, w as i32, h as i32);
```

~Note that the "bug" related to the difference between X11 and wayland is not happening anymore with the git version, but still happens on version 0.3.~ Scratch that, its still happening.

Idea of the above code is to draw part of the current surface to it self as part of a scrolling procedure.

**Comment by vhakulinen** [comment]
Following change fixed the issue:

```
diff --git a/src/context.rs b/src/context.rs
index 51c77a7..d179035 100644
--- a/src/context.rs
+++ b/src/context.rs
@@ -202,8 +202,6 @@ impl Context {
     }
 
     pub fn set_source(&self, source: &mut Pattern) {
-        let mut old_source = self.get_source();
-        old_source.dereference_by_ctx();
         unsafe {
             source.reference_by_ctx();
             ffi::cairo_set_source(self.0, source.get_ptr());
```

**Comment by vhakulinen** [comment]
I managed to fix this on my code by using `cr.pop_group_to_source()` instead of getting a reference to the patter with `cr.pop_group()` and setting it to source.

Not sure if the bug described by the first message is "valid" in a sense that its bug in this repo's code, or in my usage of cairo.

**Comment by sdroege** [comment]
This should happen anymore with the latest version on crates.io and in git. The broken refcounting with regards to patterns was fixed.

If it still happens or something else does not work, please reopen with a testcase to reproduce the problem.

@GuillaumeGomez can be closed
