### ISSUE TITLE
It's possible to observe a data race in safe Rust with the current Context API

### ISSUE THREAD

**Issue by YaLTeR** [gtk-rs/cairo#199]
In particular, it's possible to draw onto an `ImageSurface` using `Context` concurrently with using it as a source surface from a different thread, and observe the contents of the surface changing in the middle of being read from, which means it's a data race. [Data races are undefined behavior in safe Rust](https://doc.rust-lang.org/nomicon/what-unsafe-does.html), so I believe this makes the current API unsound.

Example program demonstrating the issue:
```rust
extern crate cairo;
use cairo::{Context, Format, ImageSurface};

use std::{fs::File, thread};

fn main() -> Result<(), cairo::Status> {
    // The main idea is to create a big surface and fill it with small surfaces
    // in a tiled pattern. On a separate thread, the small surface is
    // continuously filled with alternating colors, red and green. If any of
    // the small surface copies on the big surface are filled partially with
    // one color and partially with another color, it means that a data race
    // was observed, which constitutes as undefined behavior in safe Rust.

    // Create the small 32×32 surface.
    let small_surface = ImageSurface::create(Format::ARgb32, 32, 32)?;

    // Fill it with red, the initial color.
    {
        let cr = Context::new(&small_surface);
        cr.set_source_rgb(1.0, 0.0, 0.0);
        cr.paint();
    }

    // Create a second reference and spawn a second thread that fills it with
    // green and then red in a loop.
    let small_surface_clone = small_surface.clone();
    thread::spawn(move || loop {
        {
            let cr = Context::new(&small_surface_clone);
            cr.set_source_rgb(0.0, 1.0, 0.0);
            cr.paint();
        }

        {
            let cr = Context::new(&small_surface_clone);
            cr.set_source_rgb(1.0, 0.0, 0.0);
            cr.paint();
        }
    });

    // Create the big surface.
    let big_surface = ImageSurface::create(Format::ARgb32, 1024, 1024)?;

    // Leave a gap of 4 pixels between small surface copies on the big suface
    // to be able to see each individual copy of the small surface.
    const GAP: usize = 4;
    const FITS_IN_ROW: usize = (1024 - 32) / (32 + GAP) + 1;

    // In a loop, copy the small surface to the big surface in a tiled pattern.
    for j in 0..FITS_IN_ROW {
        for i in 0..FITS_IN_ROW {
            let x = i * (32 + GAP);
            let y = j * (32 + GAP);

            let cr = Context::new(&big_surface);
            cr.set_source_surface(&small_surface, x as f64, y as f64);
            cr.paint();
        }
    }

    // Save the resulting surface to a PNG file.
    big_surface
        .write_to_png(&mut File::create("output.png").unwrap())
        .unwrap();

    Ok(())
}
```
Example output that I got:
![image](https://user-images.githubusercontent.com/1794388/42688861-55c3f140-869e-11e8-8e0b-42074d58aadb.png)
Note that most of the squares are partially green and partially red which means that a data race was observed.

I'm not sure what the best way of fixing this would be. Taking the surface by a mutable reference in `Context::create()` and ensuring its uniqueness, like in `ImageSurface::get_data()`, might be sufficient, however rather limiting, just like `ImageSurface::get_data()` currently is.

I believe the underlying issue is that Cairo objects are like `Arc<T>`, except they always offer mutable access and don't provide any way of checking whether someone is currently using them mutably. A more general solution could be to wrap Cairo objects in an `Arc<RwLock<T>>` and use that instead of the built-in Cairo refcounting, which would allow doing borrowing and reference counting on the Rust side, and make it possible to safely do shared read-only access (like `ImageSurface::get_data()`, but without the unique reference check) as well as safe write access even with multiple references laying around (thanks to `RwLock`). Wrapping the surface in an `Arc<RwLock<T>>` in the example program does fix the data race.

**Comment by GuillaumeGomez** [comment]
We should prevent the cloning first. If cairo doesn't handle multiple threads, we can't allow it to be duplicated and sent between threads.

**Comment by YaLTeR** [comment]
Yeah, that's what I meant by the second possible solution: wrap it in `Arc<RwLock<T>>` and don't ever clone the inner `T`.

**Comment by GuillaumeGomez** [comment]
Absolutely, just proposed the most obvious solution.

**Comment by SimonSapin** [comment]
I believe this was fixed in https://github.com/gtk-rs/cairo/pull/233 and this can be closed. CC https://github.com/gtk-rs/cairo/issues/256. Output with cairo-rs 0.6.0:

```rust
error[E0277]: `*mut cairo_sys::cairo_surface_t` cannot be sent between threads safely
  --> src/main.rs:27:5
   |
27 |     thread::spawn(move || loop {
   |     ^^^^^^^^^^^^^ `*mut cairo_sys::cairo_surface_t` cannot be sent between threads safely
   |
   = help: within `[closure@src/main.rs:27:19: 39:6 small_surface_clone:cairo::ImageSurface]`, the trait `std::marker::Send` is not implemented for `*mut cairo_sys::cairo_surface_t`
   = note: required because it appears within the type `cairo::Surface`
   = note: required because it appears within the type `cairo::ImageSurface`
   = note: required because it appears within the type `[closure@src/main.rs:27:19: 39:6 small_surface_clone:cairo::ImageSurface]`
   = note: required by `std::thread::spawn`

error: aborting due to previous error

**Comment by sdroege** [comment]
Indeed, @GuillaumeGomez please close this :)

**Comment by GuillaumeGomez** [comment]
Sure!
