### ISSUE TITLE
How to send Surface?

### ISSUE THREAD

**Issue by pzmarzly** [gtk-rs/cairo#226]
This may be a bit of noob question.

```rust
// wv - webview
wv.connect_load_changed(move |wv, ev| {
    if ev == LoadEvent::Finished {
        wv.get_snapshot(
            SnapshotRegion::FullDocument,
            SnapshotOptions::NONE,
            None,
            move |res| {
                if let Ok(surface) = res {
                    sender.send(surface).unwrap();
                }
            },
        );
    }
});
// somewhere else
img.set_from_surface(Some(surface));
```

Results in same error almost the same as in: https://pastebin.com/RzYNmW1v (I found this paste by googling, yet no references to it. Maybe similar question was answered on IRC?)

```text
error[E0277]: `*mut cairo_sys::cairo_surface_t` cannot be sent between threads safely
   --> src/main.rs:122:16
    |
122 |             wv.get_snapshot(
    |                ^^^^^^^^^^^^ `*mut cairo_sys::cairo_surface_t` cannot be sent between threads safely
    |
    = help: within `cairo::surface::Surface`, the trait `std::marker::Send` is not implemented for `*mut cairo_sys::cairo_surface_t`
    = note: required because it appears within the type `cairo::surface::Surface`
    = note: required because of the requirements on the impl of `std::marker::Send` for `std::sync::mpsc::Sender<cairo::surface::Surface>`
    = note: required because it appears within the type `[closure@src/main.rs:126:17: 133:18 pstx:std::sync::mpsc::Sender<cairo::surface::Surface>]`
```

I tried using AtomicPtr:

```rust
let ptr = AtomicPtr::new(&mut surface);
sender.send(ptr).unwrap();
// somewhere else
let surface = ptr.load(Ordering::Relaxed);
let surface = unsafe { &*surface };
img.set_from_surface(Some(surface));
```

While this compiles, the problem seems to be that by the time I load the pointer, original closure erases Surface:

```text
cairo-surface.c:930: cairo_surface_reference: Assertion `CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&surface->ref_count)' failed.
```

The problem may come from the fact that `get_snapshot` callback closure gets called in the same thread as the main thread, blocking it (it can be tested by `thread::sleep`ing in callback function and seeing the UI freeze), yet it requires callback closure to be `Send`able. In that case it is issue for [webkit2gtk-rs](https://github.com/gtk-rs/webkit2gtk-rs). Trying to just use Surface inside callback closure:

```rust
wv.get_snapshot(
    SnapshotRegion::FullDocument,
    SnapshotOptions::NONE,
    None,
    move |res| {
        if let Ok(surface) = res {
            img.set_from_surface(Some(&surface));
        }
    },
);
```

```text
error[E0277]: `*mut gtk_sys::GtkImagePrivate` cannot be sent between threads safely
   --> src/main.rs:122:16
    |
122 |             wv.get_snapshot(
    |                ^^^^^^^^^^^^ `*mut gtk_sys::GtkImagePrivate` cannot be sent between threads safely
    |
    = help: within `[closure@src/main.rs:126:17: 134:18 pstx:std::sync::mpsc::Sender<cairo::surface::Surface>, img:gtk::auto::image::Image]`, the trait `std::marker::Send` is not implemented for `*mut gtk_sys::GtkImagePrivate`
    = note: required because it appears within the type `gtk_sys::GtkImage`
    = note: required because it appears within the type `std::marker::PhantomData<gtk_sys::GtkImage>`
    = note: required because it appears within the type `gtk::auto::image::Image`
    = note: required because it appears within the type `[closure@src/main.rs:126:17: 134:18 pstx:std::sync::mpsc::Sender<cairo::surface::Surface>, img:gtk::auto::image::Image]`
```

Maybe related to #175.

**Comment by EPashkin** [comment]
@sdroege used https://crates.io/crates/fragile in similar case: https://github.com/gtk-rs/gdk-pixbuf/blob/master/src/pixbuf.rs#L136-L142

**Comment by sdroege** [comment]
There's an example here that sends cairo surfaces around: https://github.com/gtk-rs/examples/blob/master/src/bin/cairo_threads.rs

Your problem here seems to be that you use a generic cairo surface, and those are not `Send`. You can send image surfaces to different threads, but other surfaces are bound to their threads (and in your case it would be unsafe otherwise, your surface seems to come from gdk and gdk must only be used from the main thread).

> @sdroege used https://crates.io/crates/fragile in similar case: https://github.com/gtk-rs/gdk-pixbuf/blob/master/src/pixbuf.rs#L136-L142

This only works if things are actually on the same thread, otherwise it panics.

**Comment by sdroege** [comment]
@GuillaumeGomez Can be closed
