### ISSUE TITLE
ImageSurface is different then SVG/PDF/PS Surface

### ISSUE THREAD

**Issue by jsparber** [gtk-rs/cairo#250]
I think the API for ImageSurface and the other Surface should be much more similar as they are right now.

cc @meh @vojtechkral @sdroege

**Comment by vojtechkral** [comment]
Well the thing is they are distinct in Cairo itself, see [Image surfaces](https://cairographics.org/manual/cairo-Image-Surfaces.html#cairo-image-surface-create-for-data) and [PDF surfaces](https://cairographics.org/manual/cairo-PDF-Surfaces.html) for example... In particular, image surfaces don't seem to support streaming.

Or do you have other differences in mind?

**Comment by jsparber** [comment]
Also the Svg and PDF are distinct in Cairo, anyhow they should behave all the same in the bindings IMO

**Comment by sdroege** [comment]
@jsparber Maybe you can list the API differences between the different surface types that seem wrong to you, so we can start a discussion about how those specifically could be unified.

**Comment by ekg** [comment]
It would be helpful just to have examples of how to use the svg and pdf surfaces. Right now there are none, and because of the semantic differences with the PNG surface model in cairo, the PNG based example doesn't illuminate how things are bound together for these other types.

**Comment by vojtechkral** [comment]
@ekg There's an example code in the c-tor doc, see [here] (click the little `+` if not displayed right away).

Do you think that's sufficient? How would you suggest the doc/examples be improved?

**Comment by ekg** [comment]
Thank you @vojtechkral, that exactly resolves my problem! I'll see if I can get this to work.

**Comment by ekg** [comment]
I'm now able to render a PDF, but I can't functions like these to write text on it:

```
    let surface = pdf::Writer::new(400.0, 400.0, File::create("test.pdf").unwrap());
    let ctx = Context::new(&surface);
    ctx.scale(120.0, 120.0);
    ctx.select_font_face("Arial", FontSlant::Normal, FontWeight::Normal);
    ctx.set_font_size(18.0);
    ctx.move_to(2.0, 2.0);
    ctx.show_text("hello world");
```

This always yields a blank document, at least under the multiple iterations changing position that I've done. The same code is quite happy from C to draw.

Small examples showing what is needed to get a given capability working would certainly help.

**Comment by vojtechkral** [comment]
@ekg 

> The same code is quite happy from C to draw.

Are you sure the C code was really exactly the same? Looking at your Rust code I think you are rendering outside of the PDF document dimensions due to the scale factor of `120.0` - this scales the font size of `18.0` to humongous size of `2160.0` which will likely offset the X position of the string far beyond the right edge.

Try this code for size:

```Rust
let surface = pdf::File::new(400.0, 400.0, "test.pdf");
let ctx = Context::new(&surface);
ctx.select_font_face("Arial", FontSlant::Normal, FontWeight::Normal);
ctx.move_to(10.0, 200.0);
ctx.set_font_size(18.0);
ctx.show_text("hello world");
```

If there really is a discrepancy between identic Cairo operations from C vs Rust, that would be a bug, please let me know if that's the case...

**Comment by vojtechkral** [comment]
NB. We should probably dig an example from the test code and put in the doc of pdf module...

**Comment by sdroege** [comment]
See also https://github.com/gtk-rs/cairo/pull/255

**Comment by SimonSapin** [comment]
I agree with @vojtechkral that this difference between image surfaces and PDF / PS / SVG surfaces only reflect the same differences is cairo’s own API. It is the role of bindings like cairo-rs to “translate” C idioms into Rust idioms (for example structs with `Drop` impls instead of destructor functions) but not to try to change the semantics of the API.

And there’s a reason for this difference: PDF, PS, and SVG are all formats that cairo writes to a byte stream. This byte serialization is the whole point of these surface types, so requiring a stream or file name to create the surface makes sense. This also allows cairo to write bytes incrementally in some cases, rather than keep everything in memory. On the other hand image surface is first a buffer of pixels in memory. This buffer can be loaded from or saved to PNG, but many use cases involve image surfaces without using PNG at all.

**Comment by jsparber** [comment]
@SimonSapin you are right that bindings should translate an API to be a good fit with the target language. Anyhow I'm not saying how it should work internally and I don' really care. But the API for PDF, PS and SVG is translated to rust but the imageSurface API isn't.

btw you are not required to write a svgsurface to file you can also use it as a just in memory buffer, I have do idea if this works also for PDF and PS.

**Comment by SimonSapin** [comment]
> but the imageSurface API isn't.

What do you mean?

* https://gtk-rs.org/docs/cairo/struct.ImageSurface.html#method.create
* https://gtk-rs.org/docs/cairo/struct.ImageSurface.html#method.get_data
* https://gtk-rs.org/docs/cairo/struct.ImageSurface.html#method.create_from_png
* https://gtk-rs.org/docs/cairo/struct.ImageSurface.html#method.write_to_png

> can also use it as a just in memory buffer

Yes, this is what I meant by streams. cairo-rs exposes this as generic wrappers of anything that implements the `std::io::Write` trait:

* https://gtk-rs.org/docs/cairo/pdf/struct.Writer.html
* https://gtk-rs.org/docs/cairo/ps/struct.Writer.html
* https://gtk-rs.org/docs/cairo/svg/struct.Writer.html

**Comment by jsparber** [comment]
> > but the imageSurface API isn't.
> 
> What do you mean?
> 
>     * https://gtk-rs.org/docs/cairo/struct.ImageSurface.html#method.create
> 
>     * https://gtk-rs.org/docs/cairo/struct.ImageSurface.html#method.get_data
> 
>     * https://gtk-rs.org/docs/cairo/struct.ImageSurface.html#method.create_from_png
> 
>     * https://gtk-rs.org/docs/cairo/struct.ImageSurface.html#method.write_to_png
> 

I mean that the don't feel like a rust api. I'm saying that the ImageSurface API should look something like this:
cairo_image_surface_create_for_data() should look like cairo::image::Data::new()
cairo_image_surface_create_from_png() shoudl look like cairo::png::File::new()
...

Or maybe all Surface APIs could look compliantly differently, since svg, pdf, ps don't include the word Surface at all which makes it more difficult to understand.
  
> > can also use it as a just in memory buffer
> 
> Yes, this is what I meant by streams. cairo-rs exposes this as generic wrappers of anything that implements the `std::io::Write` trait:
> 
>     * https://gtk-rs.org/docs/cairo/pdf/struct.Writer.html
> 
>     * https://gtk-rs.org/docs/cairo/ps/struct.Writer.html
> 
>     * https://gtk-rs.org/docs/cairo/svg/struct.Writer.html

I wasn't talking about the streams.  `cairo_svg_surface_create()` allows to not set a file and it allows you do use the created surface to be displayed in e.g. a gtkImage

**Comment by SimonSapin** [comment]
While I disagree with some of the complaints as they are stated in this thread, I agree that the current API for PDF/PS/SVG surfaces are more weird than they have to be. I’ve proposed another design in https://github.com/gtk-rs/cairo/issues/258.

**Comment by sdroege** [comment]
This should be better now so let's close it for now. Please create a new ticket with more details if there's still something missing.

@GuillaumeGomez can be closed :)
