### ISSUE TITLE
Surface.create_similar() should return a Result

### ISSUE THREAD

**Issue by federicomenaquintero** [gtk-rs/cairo#251]
As in #141, `cairo_surface_create_similar()` will never return NULL, but it may return a `cairo_surface_t *` with an error status.  I think `Surface::create_similar()` should return a `Result<Surface, Status>`.

**Comment by sdroege** [comment]
Yes, and probably the same for various other functions. Someone should go through them all at some point.

**Comment by EPashkin** [comment]
@federicomenaquintero Thanks for fixing
👍

**Comment by sdroege** [comment]
> @federicomenaquintero Thanks for fixing

This one is not fixed yet :)

**Comment by federicomenaquintero** [comment]
Damn, just got a librsvg bug where we panicked because Surface.create_similar() always returns a Surface :disappointed: 

I've started fixing this.  My first cut is to turn `Surface::from_raw_full() -> Result`, just like we had `ImageSurface::from_raw_full() -> Result`.  The fallout is not bad; it actually makes things like `RecordingSurface::create()` more correct; it returns an Option right now, but cairo_recording_surface_create() will never return NULL, just a surface in an error status.

I have a question about this:

```rust
#[cfg(feature = "use_glib")]
impl FromGlibPtrFull<*mut ffi::cairo_surface_t> for Surface {
    #[inline]
    unsafe fn from_glib_full(ptr: *mut ffi::cairo_surface_t) -> Surface {
        Self::from_raw_full(ptr).unwrap()
    }
}
```

This is.... wrong?  Or did we ever discuss this - the unwrap() seems perilous?

**Comment by sdroege** [comment]
> This is.... wrong? Or did we ever discuss this - the unwrap() seems perilous?

That's correct. If all you want to have returned is a concrete value instead of an Option, then the only thing we can do here is to panic if we get NULL or it doesn't work otherwise.

The Option FromGlibXXX impls would do the right thing and not panic.

**Comment by EPashkin** [comment]
And maybe better add function to `Status` that convert T to Option<T> (near `ensure_valid`) and use it in your other functions

**Comment by sdroege** [comment]
`Result::ok()` you mean?

**Comment by EPashkin** [comment]
@sdroege No, I meant in function that must return Option.

**Comment by EPashkin** [comment]
Oh, ignore this idea, I wrongly understand main issue

**Comment by federicomenaquintero** [comment]
@EPashkin I'm using your `to_result()` idea; thanks for that.  The others are already handled by `Surface.from_raw_full()`, I think.
