### ISSUE TITLE
Shouldn't the Gradient type be reexported?

### ISSUE THREAD

**Issue by RazrFalcon** [gtk-rs/cairo#272]
[This code](https://github.com/gtk-rs/cairo/blob/3bd65dad0c45fa2976684de9285492679895c9cc/src/lib.rs#L84) reexport all pattern types except Gradient. Is it missing or this is intentional?

**Comment by sdroege** [comment]
No all types should be exported. Do you want to send a PR for that?

**Comment by sdroege** [comment]
@GuillaumeGomez This one should get a bugfix release, that's rather bad :)

**Comment by RazrFalcon** [comment]
>Do you want to send a PR for that?

Sure, it's an easy fix.
