### ISSUE TITLE
Include rustfmt in CI

### ISSUE THREAD

**Issue by Hofer-Julian** [gtk-rs/cairo#290]
I noticed that rustfmt gives quite a lot feedback on how to reformat this codebase (mostly in cairo-sys-rs/src/lib.rs). On the first glance the proposed changes seem to be very reasonable, which is why I would like to suggest to add rustfmt in the CI.

The required command would be `cargo fmt --all -- --check  `

**Comment by GuillaumeGomez** [comment]
Ah right, we did it into all other repositories but not into this one...
