### ISSUE TITLE
SvgSurface path should be an Option

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/cairo#293]
Per the docs in https://www.cairographics.org/manual/cairo-SVG-Surfaces.html the filename param of  `cairo::SvgSurface::new` should be optional see

> filename | a filename for the SVG output (must be writable), NULL may be used to specify no output. This will generate a SVG surface that may be queried and used as a source, without generating a temporary file.

**Comment by sdroege** [comment]
Sounds like a good idea, do you want to provide a PR?
