### ISSUE TITLE
Possible memory leak in set_source_pixbuf

### ISSUE THREAD

**Issue by zwerdlds** [gtk-rs/cairo#309]
Hello all-
[Apologies in advance if my procedure is incorrect.  I am not a frequent GitHub user.  In addition, I am new to Rust and GTK.  Thank you for your help!]

I am trying to diagnose a memory leak in the program I have attached.  In this program, I am loading an OpenCV `Mat`, loading it into some `Bytes` and then that into a `Pixbuf`.  From there the `Pixbuf` is added to a Cairo `Context` via `set_source_pixbuf`.  The code functions correctly, except that it never releases a large portion of memory.  Removing the `set_source_pixbuf` line seems to remove the memory leak, but I also do not work with unsafe code ever.

I have forked the examples project [here](https://github.com/zwerdlds/examples/).   The demo of the leak is [here](https://github.com/zwerdlds/examples/blob/master/src/bin/cairo_pixbuf_overload.rs).  I have created a cargo target named `cairo_pixbuf_overload`.  You will need to change the image path at the top of the file in order for the program not to crash.

Can anyone take a look at this and tell me where I should start my search?  I appreciate any help.  Thank you.

**Comment by sdroege** [comment]
As asked on IRC:
```
<slomo> zwerdlds-M: does the leak go away if you do cr.set_source_rgb(0,0,0) or so after cr.paint()?
<slomo> zwerdlds-M: also try moving part of the work outside the callback. opening the file with opencv and/or creating the pixbuf. to isolate if the problem is from either of the two
```

**Comment by zwerdlds** [comment]
I've updated the project with the suggestions given, but it appears the leak still exists.

**Comment by sdroege** [comment]
What if you create a pixbuf from a simple `vec![0; width*height*3]` and not call any opencv API at all?

**Comment by zwerdlds** [comment]
I have updated the project and it appears to persist.

**Comment by sdroege** [comment]
Ok, so we have a much simpler testcase with fewer dependencies and moving parts now :) Needs someone to analyze what happens here in detail though, it looks all correct to me in the application and on the bindings side. There's something weird going on inside GTK here.

**Comment by sdroege** [comment]
How do you measure a memory leak here? Both the original version (5bea3c1a76ccd40d9f8790c77e72b65eeaf8557c) and the latest version (0fc1669ad5bd6a625f1ca92894644b128200eccf) don't show any increase in memory usage (e.g. in `top`) when repeatedly pressing the "queue redraw" button.

Which versions of gtk and cairo are you using on which platform? (Also I had to switch the opencv-32 feature to opencv-4 because that's the version I have here, but that should be unrelated)

**Comment by zwerdlds** [comment]
I am seeing unbounded memory increases in htop.  heaptrack also seems to indicate unreleased allocations.

I am on Mint Debian 18.04 AMD64.  I have libgtk 3.22.30 and libcairo2 1.15.10 installed via APT and noticed the behavior using `gtk = { version = "^0.8", features = ["v3_16"] }` in my Cargo.toml.  I will update my system and post back results tonight.

**Comment by zwerdlds** [comment]
Unfortunately I am stuck on libgtk 3.22.30 for the time being.  I will update my system ASAP, but for my edification, what libgtk version where you observing no leak on?  3.24?

**Comment by sdroege** [comment]
GTK 3.24.13 here.

What does heaptrack tell you where the memory is piling up?

**Comment by zwerdlds** [comment]
Alright.  I've moved my workstation to Arch, upgraded to the latest available OpenCV on AUR (4.2 as well) GTK etc...  and the leak is gone.  Thank you for your help.

I am willing to mark this closed, as I don't have the time to pursue this further at the moment.  My old system configuration was a fairly bland Mint install though, so this might pop up again for those folks.  It's really lame that APT doesn't provide more up-to-date packages but I guess that's also a selling point.

Thanks again for your help.  Would you like me to post the heaptrack profile?  I still have it if you think it would help.

**Comment by sdroege** [comment]
> Would you like me to post the heaptrack profile?

Yes that would be helpful, thanks :)

**Comment by zwerdlds** [comment]
[heaptrack.cairo_pixbuf_overload.2166.gz](https://github.com/gtk-rs/cairo/files/4239492/heaptrack.cairo_pixbuf_overload.2166.gz)
