### ISSUE TITLE
`cairo_ft_*` functions are assumed to be available

### ISSUE THREAD

**Issue by pkgw** [gtk-rs/cairo#325]
I believe that right now, both the `-sys` crate and the main crate assume that Cairo is built with FreeType support, i.e. that the `cairo_ft_*` functions are defined. In the main crate, these functions are used here: https://github.com/gtk-rs/cairo/blob/master/src/font/font_face.rs#L95-L105

On Windows, cairo might not be built with FreeType, as in [the conda-forge cairo package](https://github.com/conda-forge/cairo-feedstock/). We recently ran into a build issue with librsvg that seems to stem from the violation of this assumption.

If this diagnosis is correct, and there's a desire to increase the build portability to include systems where Cairo is built without FreeType, I think that another build feature would have to be added, mapping to `CAIRO_HAS_FT_FONT`.

**Comment by pkgw** [comment]
By the way ... obviously, Cairo has a ton of build-time features, and it would probably be extremely tedious to manually map all of them into Rust features plus the appropriate `cfg!` guards on surrounding code. What I did in [slurm-sys](https://github.com/pkgw/slurm-rs/blob/master/slurm-sys/build.rs#L100) is have the build.rs script run bindgen on-the-fly, so that the sys library only links to symbols actually defined in the underlying library, and then (ew) parse the bindgen output to identify which features are activated, which can be [wired up](https://github.com/pkgw/slurm-rs/blob/master/slurm/build.rs) to turn on `cfg!` features in the non-sys library. Gross for sure, but the least-bad solution I could come up when you've got a C library that has a wide array of its own "feature flags".

**Comment by sdroege** [comment]
For simplicity I would now make it another feature flag. In the future we could consider selecting these automatically based on the cairo configuration (no need to do hacks like you described: cairo provides one pkg-config file per optional feature, e.g. `cairo-ft.pc` for this case).

Do you want to provide a PR for this?

**Comment by pkgw** [comment]
Not really, but yes I can prepare one :-) I'm thinking I'd name the feature `freetype`, and maybe mark it as a "default feature" to provide continuity with previous releases?

**Comment by sdroege** [comment]
Sounds good, thanks!
