### ISSUE TITLE
Get data out of a referenced ImageSurface

### ISSUE THREAD

**Issue by jneem** [gtk-rs/cairo#329]
`ImageSurface::get_data` returns an error if the surface is referenced, but I believe it should still be possible to copy the data out safely: since neither `ImageSurface` nor `Context` is `Sync`, there shouldn't be any concurrent modifications.

Of course, there's the question of how to return the data: you can't return `&[u8]`, for reasons discussed in #279. But would you accept a PR to add a method like this?
```rust
impl ImageSurface {
    pub fn copy_data_to(&self, buf: &mut [u8]) -> Result<(), BorrowError>;

    // Or, a more general version
   pub fn with_data<F: FnOnce(&[u8])>(&self, f: F) -> Result<(), BorrowError>;
}
```

**Comment by sdroege** [comment]
The `with_data` variant looks like a good idea to me
