### ISSUE TITLE
Stride issues

### ISSUE THREAD

**Issue by PixeLInc** [gtk-rs/cairo#332]
Hey all, I hate to make this issue but I'm a bit lost at the moment and have been banging my head for hours.

I've got the following code, and don't mind the crappy error handling:
```rust
// user_image in this case is &[u8]
let image = image::io::Reader::new(Cursor::new(&user_image)).with_guessed_format().expect("Failed to read image"); 
let image_data = image.decode().unwrap().to_rgba();
let width = image_data.width() as i32;
let height = image_data.height() as i32;
      
let user_image_surface = cairo::ImageSurface::create_for_data(    
    image_data.into_raw(),    
    cairo::Format::ARgb32,
    width, 
    height,                           
    cairo::Format::ARgb32.stride_for_width(width as u32).unwrap()
);
```

But, when running and testing it out, I always get a panic with `assertion failed: len >= (height * stride) as usize'`.
I took a look at the internal data and `(height * stride)` is insanely bigger than the length, so I don't know what I'm doing wrong here.

If anyone has any idea or easier way to do this, that would be insanely appreciated.
Thanks

**Comment by GuillaumeGomez** [comment]
The problem is the `height` or the `stride`?

**Comment by PixeLInc** [comment]
*sigh* I should type things out before I make issues.
I just fixed it after I made this.

I was using `to_rgb` on the DynamicImage rather than `to_rgba` which fixed it when I changed it.

I apologize, lol. 
At least this can be here if someone else does the same stupid mistake as I do.. :P

**Comment by GuillaumeGomez** [comment]
Instead of using `cairo::Format::ARgb32`, you should used the image format directly too. ;)
