### ISSUE TITLE
Consider re-exporting `cairo-sys-rs` under `ffi`.

### ISSUE THREAD

**Issue by derekdreery** [gtk-rs/cairo#342]
I ran into a situation recently where for reasons I don't fully understand rust was trying to link to libcairo twice: once from me using `cairo-sys-fs` directly, and once from it being a dep of `cairo`. If you re-exported the "C" interface, then this wouldn't be necessary. `ffi` seems to be a standard name (used in `std`) and unlikely to clash with anything else in the crate.

**Comment by sdroege** [comment]
>  once from me using `cairo-sys-fs` directly, and once from it being a dep of `cairo`

That happens usually if you update one of the two to a version from git and keep the other from crates.io

>  `ffi` seems to be a standard name (used in `std`) and unlikely to clash with anything else in the crate.

We don't do that anywhere else but it seems useful. Should in that case probably do that for all the crates to keep it consistent.

@GuillaumeGomez What do you think?

**Comment by GuillaumeGomez** [comment]
I think this is a good idea!

**Comment by sdroege** [comment]
@derekdreery Want to give it a try in cairo and the other repos?

**Comment by derekdreery** [comment]
I'm happy to do this.
