### ISSUE TITLE
Why ImageSurface::create_for_data requires static lifetime?

### ISSUE THREAD

**Issue by TonalidadeHidrica** [gtk-rs/cairo#344]
I'm writing a simple code which uses `sdl2` and `cairo` together.  I want to update SDL2 `Texture` with cairo drawing, but there is a lifetime issue that prevents it.

The following is a snippet that cause the issue:

```rust
    let mut texture = texture_creator.create_texture_streaming(PixelFormatEnum::ARGB8888, 120, 120)?;
    texture.with_lock(None, |pixels, stride| {
        let surface = ImageSurface::create_for_data(pixels, Format::ARgb32, 120, 120, stride as i32).unwrap();
        let cr = Context::new(&surface);

        // Do some drawing with cr
    });
```
The argument of the closure, `pixels`, is alive within the scope of entire lambda, since we have no access to the pixels once the texture is unlocked.  However, `ImageSurface::create_for_data` requires a static lifetime for the `data` argument (`data: D`, `D: AsMut<[u8]> + 'static`).  Therefore, we get a lifetime error at the creation of the surface.

There are some workarounds: maybe we can write an unsafe code so that the lifetime check is ignored (though I don't know how to do it).  Otherwise, we can create a surface and do some drawing to it, and then copy the pixels to that of SDL2 texture.  But it is less efficient since it requires to copy the pixel array twice.

So my questions are:
* Why `data: D` requires a static lifetime?
* What is the best workaround?  Are there any other better way?

**Comment by sdroege** [comment]
Cairo surfaces are reference counted and it's hard-to-impossible to ensure statically and in general that a surface is actually not used anymore. That can only really be checked at runtime.

It could make sense to add a `create_for_data_unsafe()` that doesn't require this and puts the burden on you to ensure that the surface does not exist anymore at the end of the `with_lock()` closure.

Or alternatively you could create (also with a bit of unsafe code and raw pointers) a wrapper around the `pixels` that is `'static` and ideally add a runtime check at the end of the closure to ensure that it's indeed not used anymore afterwards (once the surface is destroyed the `Drop` impl of the data is called).

It would probably make most sense to add a `create_for_data_unsafe()`, and also simpler. Do you want to send a PR for that?

**Comment by TonalidadeHidrica** [comment]
Thank you for your fast reply.  In specific, what kind of operations make a surface referenced from more than one place?  Is it possible to happen in the code above?

I'm not sure how can I properly implement `create_for_data_unsafe`, so I'll first try it by myself.  When I happened to succeed, I'll send a PR.

**Comment by sdroege** [comment]
> Thank you for your fast reply. In specific, what kind of operations make a surface referenced from more than one place? Is it possible to happen in the code above?

No, your code above is ok.

> I'm not sure how can I properly implement `create_for_data_unsafe`, so I'll first try it by myself. When I happened to succeed, I'll send a PR.

Feel free to ask here for help :)

**Comment by TonalidadeHidrica** [comment]
Aside from creating unsafe variant, isn't it possible to create a safe variants with additional constraints, such as, preventing from referenced from multiple places?  For example, how about returning `Box<ImageSurface>` whose lifetime is shorter than `data` parameter?

**Comment by sdroege** [comment]
Not really as the additional references could be taken inside C code that we have no control over and where Rust lifetimes have no meaning.

**Comment by TonalidadeHidrica** [comment]
I'm afraid to ask you again, but what kind of operations make multiple references for example?

**Comment by TonalidadeHidrica** [comment]
I read the code for `create_for_data` and now have a question: what is the purpose of [storing data pointer as the user data](https://github.com/gtk-rs/cairo/blob/master/src/image_surface.rs#L59-L63)?  I once guessed it's something related with dropping, but I could not found the place where the stored data is obtained.  Since `set_user_data` also requires `'static` reference as the value, I could not implement the unsafe version that does not require static lifetime.  How can I go on?

**Comment by sdroege** [comment]
> I'm afraid to ask you again, but what kind of operations make multiple references for example?

Setting a surface as source for a context operation, for example. If you don't unset it afterwards (or set a different source) then the context will continue to have a reference to it until it is unset.

> How can I go on?

You could add a `set_user_data_ptr()` similar to the existing `get_user_data_ptr()` [here](https://github.com/gtk-rs/cairo/blob/master/src/user_data.rs) and work from that.

**Comment by TonalidadeHidrica** [comment]
Thank you.  I understood that even limiting the reference is still difficult.  And also thank you for your suggestion about adding `set_user_data_ptr`.  By the way, I came up with another unsafe workaround: converting `data` slice to raw pointer, and converting back to slice again.  It looks like this:

```rust
    pub unsafe fn create_for_data_unsafe<D: AsMut<[u8]>>(
        mut data: D,
        format: Format,
        width: i32,
        height: i32,
        stride: i32,
    ) -> Result<ImageSurface, Error> {
        let data = data.as_mut();
        let data = std::slice::from_raw_parts_mut(data.as_mut_ptr(), data.len());
        Self::create_for_data(data, format, width, height, stride)
    }
```

How do you think of it?  At least it works for the example above.

**Comment by sdroege** [comment]
That also works, yes. API-wise it would be more correct to work with a `*mut u8` and `usize` though as it's the callers responsibility to take care of lifetimes.

**Comment by TonalidadeHidrica** [comment]
You mean that the method signature should be like `(data_ptr: *mut u8, data_size: usize, format, width, height stride)` rather than `(data: D, format, width, height stride)` ?  That makes sense.  
Then, how about receiving single `Range<*mut u8>` instead of two arguments, so that it's more semantic and in the future users can use [`slice::as_mut_ptr_range`](https://doc.rust-lang.org/std/primitive.slice.html#method.as_mut_ptr_range) as shorthand?

**Comment by sdroege** [comment]
`Range` seems to be the wrong API for that, and `as_mut_ptr_range()` is also nightly-only. I expect that to be one of the discussion points in the tracking issue there :)

But yes, the signature that you suggested. Or rather, `data_size` can be omitted as it will have to be `stride * height` anyway.

**Comment by TonalidadeHidrica** [comment]
It seems that omitting `data_size` makes sense.  I found that providing `Range` without the unstabilized API is quite troublesome anyway.  I'll try creating a PR.

**Comment by TonalidadeHidrica** [comment]
@sdroege Thanks for all your kind support!

**Comment by sdroege** [comment]
Thanks for your PR :)
