### ISSUE TITLE
exit code: 0xc0000135, STATUS_DLL_NOT_FOUND

### ISSUE THREAD

**Issue by arnabanimesh** [gtk-rs/cairo#347]
I use Windows 10. I used `gvsbuild` to build `glib-2.0.pc` and then ran my program usng `cargo` in both debug and release mode. It showed the following error:

`error: process didn't exit successfully: 'target\debug\draw.exe' (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)`

Entire code and logs are mentioned in this **[Github Gist](https://gist.github.com/arnabanimesh/77d4c63ea710d2a72b26ea57ae922eda)**.

**Comment by sdroege** [comment]
Check with https://github.com/lucasg/Dependencies which DLLs are not found. You need to make sure that all DLLs used by your application are in your `PATH` or in the same directory as your application, as usual on Windows.

**Comment by arnabanimesh** [comment]
I haven't narrowed down to the dlls. But I copied dlls from gtk-build's bin folder and your dependencies folder and it ran.

How do I statically compile though?

**Comment by sdroege** [comment]
You need to get a static build of cairo and its dependencies. Check with the gvsbuild project how that can be done :)
