### ISSUE TITLE
Add online documentation

### ISSUE THREAD

**Issue by matklad** [gtk-rs/cairo#35]
I was able to build documentation locally with `cargo doc` just fine, but it would be nice if the documentation was available online.

**Comment by GuillaumeGomez** [comment]
I have to take a look at travis-cargo, but I didn't yet... Don't worry, it's on its way !

**Comment by LinusU** [comment]
I would love to see this as well. Is there any good place to publish it? Maybe Github pages?

**Comment by gkoz** [comment]
Check out http://gtk-rs.org/docs/cairo/
It's being updated by hand for the time being though.

**Comment by LinusU** [comment]
Nice! :fireworks: 

I had problems building the docs myself with `cargo doc`, gtk-rs/glib#61

**Comment by gkoz** [comment]
So here's the cargo issue: https://github.com/rust-lang/cargo/issues/1980

**Comment by gkoz** [comment]
We definitely have online documentation now.

**Comment by GuillaumeGomez** [comment]
Yes we do. ^^
