### ISSUE TITLE
Missing support for special surfaces?

### ISSUE THREAD

**Issue by dstu** [gtk-rs/cairo#56]
I can't find bindings for [surfaces for various image types](http://cairographics.org/manual/cairo-surfaces.html), like PNG or PDF. It would be very helpful to be able to render to image, as with [cairo_surface_write_to_png](http://cairographics.org/manual/cairo-PNG-Support.html#cairo-surface-write-to-png). Are these bindings expected to be supported anytime soon? (I can try to lend a hand, but I'll need to get a rubber stamp from my employer first.)

**Comment by GuillaumeGomez** [comment]
It all depends what state is the gtk-rs binding generator.

@gkoz: Any info on this ?

**Comment by gkoz** [comment]
All surfaces types should be supported eventually. Sadly the generator won't be of help here, there's no gobject metadata.

As to difficulty, the biggest challenge to implementing various backend bindings might be detecting them in the build script.

**Comment by vojtechkral** [comment]
@dstu FYI, I'm working on PNG support, see #60

**Comment by dstu** [comment]
Thanks! This will be useful for headless use, like testing the rendering of custom widget components, capturing visualizations produced by code that also produces an interactive widget, and (maybe eventually?) Web backends.

**Comment by SimonSapin** [comment]
I believe this is fixed and can be closed. See, among others:

* https://gtk-rs.org/docs/cairo/struct.ImageSurface.html#method.write_to_png
* https://gtk-rs.org/docs/cairo/pdf/struct.Writer.html

**Comment by GuillaumeGomez** [comment]
Indeed!
