### ISSUE TITLE
Minimal example

### ISSUE THREAD

**Issue by vinipsmaker** [gtk-rs/cairo#74]
Could you put the code that you've used to generate the image linked on the README.md as an example?

The rest of the documentation seems fine, but I still have no clue how to generate a OpenGL window using this. I'm planning to use cairo to develop a 2D game written in Rust. Non-OpenGL support is important too.

**Comment by GuillaumeGomez** [comment]
The example you're looking for is [here](https://github.com/gtk-rs/examples/blob/master/src/cairotest.rs). For some reasons, we can't yet use OpenGL with our binding.

**Comment by vinipsmaker** [comment]
@GuillaumeGomez, thanks. This example code is very helpful.

Is it possible to render something without gtk? Will there be OpenGL support in the future or is it a eternal limitation?

**Comment by GuillaumeGomez** [comment]
Take a look at the [PR](https://github.com/gtk-rs/gtk/pull/206), you'll certainly understand better.

**Comment by vinipsmaker** [comment]
Yes, but it doesn't answer if there will be OpenGL support.

I'm closing the issue anyway because the original question was answered. Nice project anyway. Thanks.

**Comment by GuillaumeGomez** [comment]
As the issue says, something's missing on GTK side.

**Comment by vinipsmaker** [comment]
I don't get it. Did you mentioned the correct link? I only see comments about missing doc and nothing about OpenGL.

It seems to me that Cairo can be used without gtk.

**Comment by GuillaumeGomez** [comment]
Oups! I didn't give the good url. [This](https://github.com/gtk-rs/examples/pull/44) is the good one. Sorry about that.

**Comment by vinipsmaker** [comment]
Now I understand the gtk limitation, but I still don't understand why "interest in cairo" immediately means "interest in gtk". Upstream cairo project seems to be usable without gtk and I don't understand how to use this binding without gtk.

**Comment by GuillaumeGomez** [comment]
It's pretty rare to see cairo without gtk. In order case, it was a big plus to integrate it in our gtk environment. I don't think it's possible to use our binding without gtk. But maybe I'm wrong. cc @gkoz

**Comment by gkoz** [comment]
>  how to generate a OpenGL window using this

@vinipsmaker can you explain what you mean by "generating a window"?

**Comment by vinipsmaker** [comment]
> It's pretty rare to see cairo without gtk. In our case, it was a big plus to integrate it in our gtk environment.

In my case I want to do a 2d game and I see no need for gtk. [The cairo project pages lists multiple rendering backends](http://cairographics.org/backends/):

- image
- cairo-gl
- ps
- pdf
- xlib
- xcb
- quartz
- win32
- svg
- beos
- ...

I'm interested in the cairo-gl, xcb, quartz and win32 backends (hardware-accelerated rendering and software rendering).

> I don't think it's possible to use our binding without gtk. But maybe I'm wrong. cc @gkoz

I don't see it also, but if it's not a limitation in the upstream project, it shouldn't be a limitation in the binding.

**Comment by vinipsmaker** [comment]
> @vinipsmaker can you explain what you mean by "generating a window"?

You're right. OpenGL has no such concept. It should be more appropriate to "make cairo-rs use a GL context"? I can create the context using SDL.

However, I'm also interested in software rendering (e.g. xcb) which do have the concept of windows.

**Comment by gkoz** [comment]
It seems currently [the recommended way to work with OpenGL](http://www.cairographics.org/OpenGL/) is just copying from an image surface via `glTexImage2D`.

As to various backends, we definitely should add the appropriate bindings eventually. So far our time has mostly been spent on other crates though.

**Comment by gkoz** [comment]
You may not even need backend-specific bindings, just add a binding for [`gdk_window_create_similar_surface`](https://developer.gnome.org/gdk3/stable/gdk3-Cairo-Interaction.html#gdk-window-create-similar-surface).

**Comment by vinipsmaker** [comment]
Thanks for the links on OpenGL info. Reading this binding docs, I assume it's possible to print to an image buffer. Is my assumption correct?

I think it should be possible to use this library for my game after all.

**Comment by gkoz** [comment]
In the [cairo_threads](https://github.com/gtk-rs/examples/blob/master/src/cairo_threads.rs) example I create an image surface from a preallocated buffer, draw on it and when the surface is destroyed get the buffer back. This isn't the most efficient way. There's also `get_data_unsafe`. It might be possible to implement a smart safe way to borrow the data slice.

**Comment by vinipsmaker** [comment]
I finally started to develop [my game](https://github.com/amvg-project/mvge) and I started to dig deeper in the topic (learning OpenGL, writing Rust code to integrate glium and SDL...) and I was rereading this very thread.

From what I understood, I just need to copy cairo generated images into OpenGL textures and work from there.

On the OpenGL side, I'll be using glium and the `glTexImage2D` is hidden in [`Texture2d::new`](http://tomaka.github.io/glium/glium/texture/texture2d/struct.Texture2d.html#method.new). Feel free to skip this paragraph of text.

On the cairo side, I need `ImageSurface::get_data`. I've seen #75 was merged recently and improves this very API. However, it has not been released on a new crate yet. Could you hint me on when will be the next `cairo-rs` release?

And thanks for all the support so far.

**Comment by MGageMorgan** [comment]
Hello, sorry to beat an old thread back to life, but how does one get an example like this (DEAD SIMPLE IN C):

````C
int
main (int argc, char *argv[])
{
        cairo_surface_t *surface = //Sets the Cairo surface context
            cairo_image_surface_create (CAIRO_FORMAT_ARGB32, 421, 410); //Creates Cairo image surface, sets image resolution.
        cairo_t *cr = //Declare *cr as a Cairo context.
            cairo_create (surface); //Sets the Cairo context as a pointer, *cr.

	/* Fifth triangle */
	cairo_set_source_rgba (cr, 0.60, 0.85, 0.91, 0.8); //Sets the color of the triangle.
	cairo_line_to (cr, 244, 314); //Draws a line from Point A to Point B.
	cairo_line_to (cr, 148, 375); //Draws a line from Point B to Point C.
	cairo_line_to (cr, 70, 184); //Draws a line from Point C back to Point A.
	cairo_close_path (cr); //Finishes the connections between Points A and C, closes off the figure.

	cairo_fill_preserve (cr); //Preserve fill so shape doesn't output as an outline.
	cairo_set_source_rgba (cr, 0.60, 0.85, 0.91, 0.8); //Sets the color of the triangle (again)
	cairo_stroke (cr); //Draw the final shape

	/* Write output and clean up */
        cairo_surface_write_to_png (surface, "../images/triangle5-color.png"); //Name the resulting image as triangle5-color.png
        cairo_destroy (cr); //Destroy the context pointer, frees up memory and/or lag
        cairo_surface_destroy (surface); //Destroy the surface pointer, frees up memory and/or lag

        return 0; //No numbers needed!!
}
````

into Rust? That's drawing a simple triangle using the info found in the Cairo tutorial on the Cairo website. It generates a PNG. I can't seem to figure out how to do this in Rust (I'm new, but I was also new to C when I first started using Cairo - without Gtk at all whatsoever).

**Comment by MGageMorgan** [comment]
Could someone who actually knows how to use this extensively port the tutorial? I can't simply because I don't know how to use this, but would if I could. The above uses many concepts from the tutorial used by MOST bindings, This has like 2 examples, neither of which show how to write dead simple, barebones programs which generate SVGs or PNGs.

**Comment by EPashkin** [comment]
For start you can look https://github.com/gtk-rs/examples/blob/master/src/bin/cairotest.rs, this use gtk to draw, but can give you main idea how to draw in cairo.
Porting your example is straightforward, only possible problem is https://github.com/gtk-rs/cairo/blob/master/src/image_surface_png.rs#L81 that need `features = ["png"]` to use.
Also you can use cairo without glib if add `default-features = false` on cairo dependence

**Comment by MGageMorgan** [comment]
@EPashkin, sorry for the delay in response,
 
```rust
   drawable(500, 500, |_, cr| {
        cr.set_dash(&[3., 2., 1.], 1.);
        assert_eq!(cr.get_dash(), (vec![3., 2., 1.], 1.));

        cr.scale(500f64, 500f64);

        cr.set_source_rgb(250.0/255.0, 224.0/255.0, 55.0/255.0);
        cr.paint();

        cr.set_line_width(0.05);

        // border
        cr.set_source_rgb(0.3, 0.3, 0.3);
        cr.rectangle(0.0, 0.0, 1.0, 1.0);
        cr.stroke();

        cr.set_line_width(0.03);

        // draw circle
        cr.arc(0.5, 0.5, 0.4, 0.0, PI * 2.);
        cr.stroke();
```
The question is, how do I do this type of stuff **WITHOUT** GtkDrawables? Porting the above is not straightforward, especially when I can't find anything about this

```c
       cairo_surface_t *surface = //Sets the Cairo surface context
            cairo_image_surface_create (CAIRO_FORMAT_ARGB32, 421, 410); //Creates Cairo image surface, sets image resolution.
        cairo_t *cr = //Declare *cr as a Cairo context.
            cairo_create (surface); //Sets the Cairo context as a pointer, *cr.
```
in the docs. I feel like mostly all the drawing operations are complete here, but there's no example in the binding how to do this pointer garbage safely in Rust.

I looked at the second link, and I have no clue how this works:

```rust
write_to_png<W: Write>(&self, stream: &mut W) -> Result<(), IoError>
```

I'm not native to the Rust language. The second thing I've tried is this, but I'm sure as most of the experienced know just by looking at it, it won't work:

```rust
extern crate cairo_sys;
use cairo_sys::cairo_image_surface_create;
use cairo_sys::cairo_surface_t;
use cairo_sys::cairo_create;
use cairo_sys::cairo_set_source_rgba;

fn main() {
    cairo_image_surface_create(CAIRO_FORMAT_ARGB32,
                               421,
                               410);

    let surface: *mut = cairo_sys::cairo_surface_t{};                               
    cairo_create(cairo_surface_t{});

    cairo_set_source_rgba(*mut cairo_t,
                          0,
                          0.79,
                          0.83,
                          0.8)

    cairo_scale(*mut cairo_t, 1.0, 1.0)

    cairo_line_to(*mut cairo_t, 143, 30)
    cairo_line_to(*mut cairo_t, 198, 176)
    cairo_line_to(*mut cairo_t, 23, 281)

    cairo_close_path(*mut cairo_t)

    cairo_fill_preserve(*mut cairo_t)

    cairo_set_source_rgba(*mut cairo_t,
                          0,
                          0.79, 
                          0.83,
                          0.8)

    cairo_stroke(*mut cairo_t)

    write_to_png<W: Write>(&self, stream: &mut W) -> Result<(), IoError>

    cairo_destroy(*mut cairo_t)

    cairo_surface_destroy(*mut cairo_surface_t)
}
```

I'm about to give up. I'm trying to learn Rust, but a project with Cairo doesn't look like it's gonna work unless I write the FFI bindings myself, which I'm not too keen to do. @EPashkin, thanks for at least responding.

**Comment by EPashkin** [comment]
IMHO You don't need `cairo_sys`, only `cairo`.
Code will look like this:
```rust
extern crate cairo;

use cairo::{Context, ImageSurface, Format};

...
let surface = ImageSurface::create(Format::ARgb32, 421, 410); //http://gtk-rs.org/docs/cairo/struct.ImageSurface.html#method.create
let cr = Context::new(&surface); //http://gtk-rs.org/docs/cairo/struct.Context.html#method.new
cr.set_source_rgba(0, 0.79, 0.83, 0.8);
cr.paint();
...
let file = File::create("file.png").unwrap();
surface.write_to_png(&mut file);
```

**Comment by MGageMorgan** [comment]
@EPashkin So I tried to format the above into a working example, and only came across one roadblock:

```rust
extern crate cairo;

use std::error::Error;
use std::fs::File;
use std::io::prelude::*;
use std::path::Path;
use cairo::{Context, ImageSurface, Format};

fn main() {
    let surface = ImageSurface::create(Format::ARgb32, 421, 410); //http://gtk-rs.org/docs/cairo/struct.ImageSurface.html#method.create
    let cr = Context::new(&surface); //http://gtk-rs.org/docs/cairo/struct.Context.html#method.new
    cr.set_source_rgba(0.0, 0.79, 0.83, 0.8);
    cr.paint();

    let file = File::create("file.png").unwrap();
    surface.write_to_png(&mut file);
}
```
SOOOOO CLOSE...

```
error[E0599]: no method named `write_to_png` found for type `cairo::ImageSurface` in the current scope
  --> src/main.rs:16:13
   |
16 |     surface.write_to_png(&mut file);
   |             ^^^^^^^^^^^^

error: aborting due to previous error
```

If this gets fixed, is it the end of the road or will it find something else to latch onto and yell about?

**Comment by MGageMorgan** [comment]
Oh, hold up forgot to set Cargo.toml to have the PNG feature...I'll edit this if the results change...

**Comment by EPashkin** [comment]
Yes, something like that.
IMHO we don't added it as normal example to https://github.com/gtk-rs/examples/ as is write files and it too simple.
@GuillaumeGomez Maybe I wrong and we better have example with something like this, but with some different drawing? Or just link previous comment somewhere?

**Comment by MGageMorgan** [comment]
As someone who just recently began to port a previous project in Cairo to rust, I'm gonna say that an example for PNGs would be greatly appreciated. To me, at least, I didn't know how to properly use surfaces and contexts in Rust. So as well as the addition to Cargo.toml in the first place (not obvious it was needed - someone had to tell me), there is a PNG example in every other binding, for example: 

https://github.com/pygobject/pycairo/blob/master/examples/cairo_snippets/snippets_png.py

Or:
http://www.mgsloan.com/cairo_tut/stroke.cs

**Comment by GuillaumeGomez** [comment]
Adding some drawings (very simple but still) would be better IMHO.

**Comment by EPashkin** [comment]
And add it to examples repo?

**Comment by GuillaumeGomez** [comment]
Once drawings are added, then totally!

**Comment by EPashkin** [comment]
Ok, I do it

**Comment by GuillaumeGomez** [comment]
Thanks! :)

**Comment by martinszy** [comment]
I just found this thread googling and it really helped.

**Comment by MGageMorgan** [comment]
@martinszy Remember when they told you to ask questions because more likely than not someone else is also having the same problem? XD

This comment makes me feel a lot less stupid now ;-)

No, but seriously it's easy to see that Rust programmers sometimes overlook simple stuff that isn't obvious to beginners. I went and did the Rust By Example book in July and August and learned many things about the standard library. 

Unfortunately, the stdlib for Rust still has some hackish features (as of summer) and I didn't have time to learn it fully - I'm now a CS freshman in college. When doing certain things for structs (don't remember exact purpose) I remember it told me to open up the stdlib docs and copy an exact function signature from it. It was like, "Why is this such a hack for a feature that should be simple."

**Comment by ekg** [comment]
I've run into this problem. @MGageMorgan spoke my mind when they pointed out how simple the "write a PNG using cairo" example in C is. 

They also ran into exactly the same gotcha as I did.

Here's my code:

```
# Cargo.toml
[dependencies]
png = "0.9.0"
cairo-rs = "0.6.0"
```

```rust
extern crate cairo;

use std::env;
use std::fs::File;
use cairo::{Context, Format, ImageSurface};

fn main() {

    let surface = ImageSurface::create(Format::ARgb32, 120, 120).expect("Can't create surface");
    let cr = Context::new(&surface);
    // Examples are in 1.0 x 1.0 coordinate space                                                                                                              
    cr.scale(120.0, 120.0);

    // Drawing code goes here                                                                                                                                  
    cr.set_line_width(0.1);
    cr.set_source_rgb(0.0, 0.0, 0.0);
    cr.rectangle(0.25, 0.25, 0.5, 0.5);
    cr.stroke();

    let mut file = File::create("file.png").expect("Couldn't create 'file.png'");
    match surface.write_to_png(&mut file) {
        Ok(_) => println!("file.png created"),
        Err(_) => println!("Error create file.png"),
    }

}
```

And... boom:

```
error[E0599]: no method named `write_to_png` found for type `cairo::ImageSurface` in the current scope
  --> src/main.rs:20:19
   |
20 |     match surface.write_to_png(&mut file) {
   |                   ^^^^^^^^^^^^

error: aborting due to previous error
```

I know that there is a steep learning curve for any new language, but examples that are fully functional and self-contained really go a long way to helping people see what to do and how to get started. Is there an example of how to use this library to just draw a tiny triangle and write it to a file?

@EPashkin there is nothing too simple. The simplest pieces are the best place to start.
