### ISSUE TITLE
Add tests for Path::iter()

### ISSUE THREAD

**Issue by federicomenaquintero** [gtk-rs/cairo#87]
I'm starting to rust-ify parts of librsvg.  In there, sometimes I need to take apart a cairo_path_t and look at the segments by hand.  I noticed that gtk-rs/cairo has a very convenient Path::iter() which gives me exactly what I need!

I'd like to have a couple of tests for the path iterator and PathSegments in general.  Would you be interested in a pull request that adds tests like these inside the cairo module?  (I think the gtk-rs/tests module is for runnable-by-hand tests, not unit tests for little pieces; is this correct?)

**Comment by GuillaumeGomez** [comment]
Sure! Tests and examples are always appreciated.

**Comment by federicomenaquintero** [comment]
I started writing tests and this came up.  The start of the test code goes like this:

    #[cfg(test)]
    mod tests {
        use super::*;
        use context::*;
        use image_surface::*;
        use ffi::enums::Format;

        fn make_cr() -> Context {
            let surface = ImageSurface::create(Format::Rgb24, 1, 1);

            Context::new(&surface)
        }

        #[test]
        fn empty_path_doesnt_iter() {
            let cr = make_cr();

            let path = cr.copy_path();

            assert!(path.iter().next().is_none());
        }
`

But when the test runs, it hits an assertion inside c_vec:

    ---- paths::tests::empty_path_doesnt_iter stdout ----
            thread 'paths::tests::empty_path_doesnt_iter' panicked at 'assertion failed: base != ptr::null_mut()', /home/federico/.cargo/registry/src/github.com-1ecc6299db9ec823/c_vec-1.0.12/src/c_vec.rs:65
    stack backtrace:
       1:     0x55c57dc39a4f - std::sys::backtrace::tracing::imp::write::h82353b94d9957b5a
       2:     0x55c57dc3d1eb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hd08c9fd28a21a931
       3:     0x55c57dc3cddc - std::panicking::default_hook::h9f5ce461fe95b992
       4:     0x55c57dc30f5d - std::panicking::rust_panic_with_hook::hfb9137c9fa89bbb0
       5:     0x55c57dbf6997 - std::panicking::begin_panic::h91a119e8e2811f21
                            at src/libstd/panicking.rs:328
       6:     0x55c57dbf760e - _<c_vec..CVec<T>>::new::h84c3ddbccdcb9a14
                            at /home/federico/src/gtk-rs/cairo/src/<std macros>:3
       7:     0x55c57dbf758f - cairo::paths::Path::iter::h1af455054fc746f9
                            at /home/federico/src/gtk-rs/cairo/src/paths.rs:44
       8:     0x55c57dbf8207 - cairo::paths::tests::empty_path_doesnt_iter::h2932713d195e9b90
                            at /home/federico/src/gtk-rs/cairo/src/paths.rs:128

This happens in Path::iter(), when calling CVec::new(data_ptr=NULL, length=0) - that function asserts that data_ptr is not null.

However, that is the kind of cairo_path_t that cairo_copy_path() returns for an empty path.

I'm not sure about these two options:

- Check for this situation in paths.rs, and deal with it there.
- Make CVec::new() understand that pointer=null and length=0 is a C idiom for "empty array".

What do you prefer?

**Comment by federicomenaquintero** [comment]
You can see the tests in paths.rs from https://github.com/federicomenaquintero/cairo/tree/path-tests

**Comment by EPashkin** [comment]
IMHO better fix `Path::iter()`

**Comment by federicomenaquintero** [comment]
Done!  Submitted a pull request.

**Comment by federicomenaquintero** [comment]
The pull request got merged and the tests are in place; closing this issue now.
