### ISSUE TITLE
Need to be able to Path::wrap() publically

### ISSUE THREAD

**Issue by federicomenaquintero** [gtk-rs/cairo#88]
I'm porting parts of librsvg to Rust; it uses Cairo internally.

At some point I get a cairo_path_t from the C code.  However, gtk-rs/cairo doesn't make ffi::cairo_path_t public.

I added a simple

  pub use ffi::cairo_path_t as cairo_path_t;

to cairo/lib.rs, so I can then

extern crate cairo;

extern "C" {
    fn rsvg_path_builder_copy_path (builder: *mut RsvgPathBuilder) -> *mut cairo::cairo_path_t;
}

fn my_stuff (builder: *mut RsvgPathBuilder) {
    let cairopath: *mut cairo::cairo_path_t;

    unsafe { cairopath = rsvg_path_builder_copy_path (builder); }
    let path = cairo::Path::wrap (cairopath);
    ... do stuff with path ...
}

at which point I have a proper cairo::Path out of its ::wrap().

I'm not sure if adding that "pub use ... as cairo_path_t" is the best solution, though it seemed easy enough :)  Ideas are appreciated.

**Comment by federicomenaquintero** [comment]
By the way, I similarly envision the need to wrap a cairo_t when I get one from the C code.  Maybe this is a general pattern that needs to be made available - to wrap Cairo objects one gets from C, so that code can be migrated to Rust piece by piece?

**Comment by federicomenaquintero** [comment]
You can look at the code here - https://github.com/GNOME/librsvg/blob/rustification/rust/src/marker.rs#L371

**Comment by gkoz** [comment]
The `cairo_t` types are being imported from the [`cairo-sys`](https://github.com/gtk-rs/cairo/tree/master/cairo-sys-rs) crate and you can do the same in your code. Unless I'm missing some obvious problem with that.

BTW `Path::wrap` not being marked `unsafe` is a bug, looks like it hasn't been unified with the other types: [wrapping `cairo_t *` uses a trait](https://github.com/gtk-rs/cairo/blob/master/src/context.rs#L53-L66) defined in [`glib::translate`](http://gtk-rs.org/docs/glib/translate/index.html). With `Path` it would probably look like

```rust
let path = unsafe { from_glib_full(rsvg_path_builder_copy_path (builder)); }
```

From a brief look around I can see another potential safety hazard. It appears that `librsvg` may be skipping some `libcairo` resource management functions. This crate destroys a path via `cairo_path_destroy`. If the path happens to be allocated by `librsvg` in an incompatible way it will get ugly.

---

Generally this crate is not in the best possible shape so if you intend to use it seriously some redesigns may need to happen.

**Comment by federicomenaquintero** [comment]
> The cairo_t types are being imported from the cairo-sys crate and you can do the same in your code. 

Uuuh, do you see anything wrong with the following?  I put this in my Cargo.toml:

[dependencies.cairo-rs]
git = "https://github.com/gtk-rs/cairo.git"

And I have this in my markers.rs:

extern crate libc;
extern crate cairo;
extern crate cairo_sys;

But "cargo build" complains with

cargo build
   Compiling rsvg_internals v0.0.1 (file:///home/federico/src/librsvg-latest/rust)
src/marker.rs:3:1: 3:24 error: can't find crate for `cairo_sys` [E0463]
src/marker.rs:3 extern crate cairo_sys;

If this looks like a total newbie mistake, you are totally right; I am one :)

I'll take a look at glib::translate; thanks.  Also, about resource management - thanks for catching that!  I'll fix it.

**Comment by GuillaumeGomez** [comment]
Take a look at the name [here](https://github.com/gtk-rs/cairo/blob/master/Cargo.toml#L29-L31).

**Comment by federicomenaquintero** [comment]
Perfect, thank you.  I have the following and now it works.  I didn't realize that crates with different names can be in fact declared to come from the same repository.

[dependencies.cairo-sys-rs]
git = "https://github.com/gtk-rs/cairo.git"

[dependencies.cairo-rs]
git = "https://github.com/gtk-rs/cairo.git"

I'll close the issue, as it was a problem on my end.

**Comment by federicomenaquintero** [comment]
By the way!  I am willing to put in work to make the Cairo module really good.  Just tell me what needs doing :)

**Comment by GuillaumeGomez** [comment]
Well, take a look at the issues then if you want to start somewhere. There is also a big one [here](https://github.com/gtk-rs/pango/issues/31) which needs some love. Thanks! :)

**Comment by federicomenaquintero** [comment]
Will do that; thanks!

**Comment by gkoz** [comment]
@federicomenaquintero also in general if some design seems wrong there's a chance it is, there're a few consistencies, so please don't hesitate to open issues.
